#!/usr/bin/env python3
"""
Interactive setup for the Okta MCP server.

Retrieves the Okta API token from Keeper and writes a .env file.

Usage:
    python local_okta_mcp/setup.py
    python local_okta_mcp/setup.py --reconfigure
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

ENV_FILE = Path(__file__).parent.parent / ".env"

# ─────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────

def _print_header(text: str) -> None:
    print(f"\n{'─' * 60}")
    print(f"  {text}")
    print(f"{'─' * 60}")


def _prompt(label: str, default: str = "", secret: bool = False) -> str:
    """Prompt the user for input, with an optional default."""
    if default:
        display_default = "****" if secret else default
        prompt_str = f"{label} [{display_default}]: "
    else:
        prompt_str = f"{label}: "

    while True:
        if secret:
            import getpass
            value = getpass.getpass(prompt_str)
        else:
            value = input(prompt_str).strip()

        if value:
            return value
        if default:
            return default
        print("  (required – please enter a value)")


def _load_env() -> dict[str, str]:
    """Parse the existing .env file into a dict."""
    env: dict[str, str] = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                env[k.strip()] = v.strip().strip('"').strip("'")
    return env


def _write_env(values: dict[str, str]) -> None:
    """Write key=value pairs to .env, preserving any unrelated lines."""
    lines = []
    if ENV_FILE.exists():
        existing = _load_env()
        existing.update(values)
        values = existing

    lines.append("# Okta MCP – generated by setup.py")
    for k, v in values.items():
        lines.append(f"{k}={v}")
    ENV_FILE.write_text("\n".join(lines) + "\n")
    print(f"\n  ✓  Wrote {ENV_FILE}")


# ─────────────────────────────────────────────────────────────
# Keeper integration
# ─────────────────────────────────────────────────────────────

def _keeper_available() -> bool:
    try:
        result = subprocess.run(
            ["keeper", "version"],
            capture_output=True, text=True, timeout=10
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def _keeper_run(args: list[str], timeout: int = 30) -> tuple[str, int]:
    try:
        result = subprocess.run(
            ["keeper"] + args,
            capture_output=True, text=True, timeout=timeout
        )
        return result.stdout.strip(), result.returncode
    except FileNotFoundError:
        return "", -1
    except subprocess.TimeoutExpired:
        return "", -2


def _keeper_search(query: str) -> list[dict]:
    """Search Keeper records and return a list of {uid, title} dicts."""
    out, code = _keeper_run(["search", "--format=json", query])
    if code != 0 or not out:
        # Fallback: plain-text search output
        out, code = _keeper_run(["search", query])
        if code != 0 or not out:
            return []
        # Parse plain-text table rows: UID  Title  ...
        records = []
        for line in out.splitlines()[1:]:  # skip header
            parts = line.split()
            if len(parts) >= 2:
                records.append({"uid": parts[0], "title": " ".join(parts[1:])})
        return records
    try:
        data = json.loads(out)
        if isinstance(data, list):
            return [{"uid": r.get("uid", r.get("record_uid", "")), "title": r.get("title", "")} for r in data]
    except json.JSONDecodeError:
        pass
    return []


def _keeper_get_password(uid: str) -> str | None:
    """Retrieve the password field from a Keeper record."""
    # Try JSON format first
    out, code = _keeper_run(["get", "--format=json", uid])
    if code == 0 and out:
        try:
            record = json.loads(out)
            # Handle both flat and nested formats
            password = (
                record.get("password")
                or record.get("fields", {}).get("password")
                or _extract_field(record, "password")
            )
            if password:
                return str(password)
        except json.JSONDecodeError:
            pass

    # Fall back to plain-text output and look for "Password: " line
    out, code = _keeper_run(["get", uid])
    if code == 0 and out:
        for line in out.splitlines():
            if line.lower().startswith("password:"):
                return line.partition(":")[2].strip()

    return None


def _extract_field(record: dict, field_name: str) -> str | None:
    """Walk nested Keeper record structures to find a named field."""
    for key in ("fields", "custom_fields"):
        for item in record.get(key, []):
            if isinstance(item, dict):
                if item.get("type") == field_name or item.get("label", "").lower() == field_name:
                    val = item.get("value")
                    if isinstance(val, list) and val:
                        return str(val[0])
                    if val:
                        return str(val)
    return None


def _keeper_get_url(uid: str) -> str | None:
    """Retrieve the URL field from a Keeper record."""
    out, code = _keeper_run(["get", "--format=json", uid])
    if code == 0 and out:
        try:
            record = json.loads(out)
            url = (
                record.get("url")
                or record.get("login_url")
                or _extract_field(record, "url")
            )
            if url:
                return str(url)
        except json.JSONDecodeError:
            pass
    out, code = _keeper_run(["get", uid])
    if code == 0 and out:
        for line in out.splitlines():
            if line.lower().startswith("url:") or line.lower().startswith("login url:"):
                return line.partition(":")[2].strip()
    return None


# ─────────────────────────────────────────────────────────────
# Setup steps
# ─────────────────────────────────────────────────────────────

def step_okta_url(existing: dict) -> str:
    _print_header("Step 1 of 3 – Okta organisation URL")
    print(
        "  Enter your Okta org URL.\n"
        "  Examples:  https://acme.okta.com   or   https://acme.oktapreview.com\n"
    )
    default = existing.get("OKTA_CLIENT_ORGURL", "")
    url = _prompt("Okta org URL", default=default)
    url = url.rstrip("/")
    if not url.startswith("http"):
        url = f"https://{url}"
    return url


def step_org_domain(existing: dict, org_url: str) -> str:
    _print_header("Step 2 of 3 – Organisation email domain (optional)")
    print(
        "  If set, users can be looked up by  first.last  short-name\n"
        "  (the domain is appended automatically).\n"
        "  Leave blank to require full email addresses.\n"
        "  Example:  acme.com\n"
    )
    default = existing.get("OKTA_ORG_DOMAIN", "")
    domain = input(f"Email domain [{default}]: ").strip()
    return domain or default


def step_api_token(existing: dict) -> str:
    _print_header("Step 3 of 3 – Okta API token")

    keeper_ok = _keeper_available()
    if keeper_ok:
        print("  Keeper CLI detected.\n")
    else:
        print(
            "  Keeper CLI not found (install from https://keepersecurity.com/secrets-manager.html).\n"
            "  You will be prompted to enter the token manually.\n"
        )

    token: str | None = None

    if keeper_ok:
        search_hint = _prompt(
            "  Search Keeper for (e.g. 'okta api token')",
            default="okta api token",
        )
        print(f"\n  Searching Keeper for '{search_hint}'…")
        records = _keeper_search(search_hint)

        if not records:
            print("  No matching records found in Keeper.")
        else:
            print(f"\n  Found {len(records)} record(s):\n")
            for i, rec in enumerate(records, 1):
                print(f"    [{i}]  {rec['title']}  ({rec['uid']})")
            print(f"    [0]  Enter token manually\n")

            while True:
                choice = input("  Select record number: ").strip()
                if choice == "0":
                    break
                try:
                    idx = int(choice) - 1
                    if 0 <= idx < len(records):
                        uid = records[idx]["uid"]
                        print(f"\n  Retrieving password from Keeper record '{records[idx]['title']}'…")
                        token = _keeper_get_password(uid)
                        if token:
                            print("  ✓  Token retrieved from Keeper.")
                        else:
                            print("  ✗  Could not read password field. Enter token manually.")
                        break
                    else:
                        print("  Invalid selection.")
                except ValueError:
                    print("  Please enter a number.")

    if not token:
        print(
            "\n  Enter your Okta API token.\n"
            "  (Generate one in Okta Admin → Security → API → Tokens)\n"
        )
        existing_masked = "****" if existing.get("OKTA_API_TOKEN") else ""
        token = _prompt("Okta API token", default=existing_masked, secret=True)
        if token == "****":
            token = existing["OKTA_API_TOKEN"]

    return token


def step_verify(org_url: str, token: str) -> bool:
    _print_header("Verifying connection…")
    try:
        import httpx
        headers = {
            "Authorization": f"SSWS {token}",
            "Accept": "application/json",
        }
        resp = httpx.get(f"{org_url}/api/v1/users?limit=1", headers=headers, timeout=15)
        if resp.status_code == 200:
            print("  ✓  Successfully connected to Okta API.")
            return True
        else:
            body = resp.json() if resp.content else {}
            print(f"  ✗  Okta returned HTTP {resp.status_code}: {body.get('errorSummary', resp.text[:120])}")
            return False
    except Exception as exc:
        print(f"  ✗  Connection failed: {exc}")
        return False


# ─────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(description="Set up Okta MCP .env file")
    parser.add_argument("--reconfigure", action="store_true", help="Overwrite existing .env")
    parser.add_argument("--no-verify", action="store_true", help="Skip connection test")
    args = parser.parse_args()

    existing = _load_env()

    if existing and not args.reconfigure:
        print(f"\n  .env already exists at {ENV_FILE}")
        print(f"  OKTA_CLIENT_ORGURL = {existing.get('OKTA_CLIENT_ORGURL', '(not set)')}")
        print(f"  OKTA_API_TOKEN     = {'(set)' if existing.get('OKTA_API_TOKEN') else '(not set)'}")
        print(f"  OKTA_ORG_DOMAIN    = {existing.get('OKTA_ORG_DOMAIN', '(not set)')}\n")
        reconf = input("  Reconfigure? [y/N]: ").strip().lower()
        if reconf != "y":
            print("  Keeping existing .env. Done.")
            return 0

    print("\n  Okta MCP – environment setup")
    print("  Press Enter to accept a default shown in [brackets].\n")

    org_url = step_okta_url(existing)
    org_domain = step_org_domain(existing, org_url)
    api_token = step_api_token(existing)

    values: dict[str, str] = {
        "OKTA_CLIENT_ORGURL": org_url,
        "OKTA_API_TOKEN": api_token,
    }
    if org_domain:
        values["OKTA_ORG_DOMAIN"] = org_domain

    _write_env(values)

    if not args.no_verify:
        ok = step_verify(org_url, api_token)
        if not ok:
            print("\n  Setup completed but connection check failed.")
            print("  Verify OKTA_CLIENT_ORGURL and OKTA_API_TOKEN, then re-run setup.")
            return 1

    print("\n  Setup complete.  Start the MCP server with:\n")
    print("      python local_okta_mcp/main.py\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
